# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d5ed14d70f307c58e002d8e48ea0fefd4ac9ef35614bc911c906ae338eadf628ca2e31aba5e101a8f64613adc971b76e875dc794a78e94f5382db462210779

test:
  secret_key_base: 96afe4c91a8fb0f78925f0fb381b1dbd153d27ca8614bc83449331ab138fc4a7300655908ffc5d4f12ca7bcf4a124b72ad532aefd673c0ff30bf628739b80a14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
